#Window size
WINDOW_WIDTH    = 1440
WINDOW_HEIGHT   = 900

#Component sizes
BOARD_BUTTON_WIDTH  = int((WINDOW_HEIGHT - 100) /8)
BOARD_BUTTON_HEIGHT = BOARD_BUTTON_WIDTH

#Positions
BOARD_BUTTON_START_X = int(WINDOW_WIDTH/2 - 4*BOARD_BUTTON_WIDTH)
BOARD_BUTTON_START_Y = int(WINDOW_HEIGHT/2 - 4*BOARD_BUTTON_HEIGHT)

#Colors
BUTTON_COLOR_DARK   = (100, 100, 100)
BUTTON_COLOR_LIGHT  = (195, 195, 195)
TEXT_BOX_BG_COLOR   = (255, 255, 255)